name: Feature branch auto merge

permissions: read-all

on:
  push:
    branches:
      - main  # Set a branch to deploy
      
env:

  REPO: https://shuyama1:${{secrets.GITHUB_TOKEN}}@github.com/shuyama1/mm-ci-test.git

  FEATURE_BRANCH: feature-branch-test-branch-2

#   MAIN_REPO: https://github.com/shuyama1/mm-ci-test.git

#   MAIN_BRANCH: main

jobs:
  merge:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    steps:
    - name: Merge with main
      run: |
        git clone ${{env.REPO}} -b ${{env.FEATURE_BRANCH}} tmp
        cd tmp
        git config user.name "Automerge Bot"
        git config user.email "bot@example.com"
        git merge origin/main

