name: Auto PR to sync major release branch with machineType

permissions: read-all

on:
  schedule:
    - cron: '*/1 * * * *'

jobs:
  pull-request:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - name: pull-request
        run: |
          gh pr create --head main --base FEATURE-BRANCH-testing --title "Merge main branch" --body "This is for testing"