name: Test Input Values for Schedule GHA Job

permissions:
  issues: write

on:
  workflow_dispatch:
    inputs:
      since:
        description: "The date to backfill tickets since in YYYY-MM-DD format"
        required: true
        default: '1973-01-01'
      dry_run:
        description: "Dry run (no changes will be made to issues)"
        type: boolean
  schedule:
        - cron: '*/5 * * * *' # every 5 min

jobs:
  test-job:
    runs-on: ubuntu-22.04
    steps:
    - name: Print out values
      run: |
        #!/usr/bin/env bash
        echo "Print out input values"
        echo "${{inputs.since}}"
        echo "${{inputs.dry_run}}"